version: "3.3"
services:
    mariadb:
        build: ./requirements/mariadb/
        container_name: "mariadb"
        env_file: ./.env
        restart: always
        volumes:
            - "db:/var/lib/mysql"
    wordpress:
        build: ./requirements/wordpress
        container_name: "wordpress"
        env_file: ./.env
        restart: always
        depends_on:
            - "mariadb"
        volumes:
            - "wp:/var/www/html"
    nginx:
        build: ./requirements/nginx
        container_name: "nginx"
        env_file: ./.env
        restart: always
        depends_on:
            - "mariadb"
            - "wordpress"
        stdin_open: true
        tty: true
        ports:
            - "443:443"
        volumes:
            - "wp:/var/www/html"
volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/alvrodri/data/mariadb
    wp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/alvrodri/data/mariadb